name: Use conda-build to build and test

on: push

jobs:
  build-and-test:
    name: ${{ matrix.os }} py${{ matrix.python-version }}
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash -l {0}
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.8"]
        os: ["ubuntu-latest", "macos-latest", "windows-latest"]
        include:
          - os: ubuntu-latest
            environment-file: ci/requirements-linux.yml
          - os: macos-latest
            environment-file: ci/requirements-macos.yml
          - os: windows-latest
            environment-file: ci/requirements-windows.yml

    steps:
      - uses: actions/checkout@v2
      - uses: conda-incubator/setup-miniconda@v2
        with:
          python-version: ${{ matrix.python-version }}
          miniconda-version: latest
          channels: conda-forge
      - name: Install conda-build
        run: |
          conda install conda-build
      - name: Run conda-build
        run: |
          conda-build conda-recipe
